package group5.webapp.FinalProjectOOP.models.GetData;

import group5.webapp.FinalProjectOOP.FinalProjectOopApplication;
import group5.webapp.FinalProjectOOP.models.*;
import group5.webapp.FinalProjectOOP.repositories.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

import javax.transaction.Transactional;

@EnableJpaRepositories
public class GetData {

    @Autowired
    CategoryRepository categoryRepository;

    @Autowired
    ProductRepository productRepository;

    @Autowired
    ProductImageRepository productImageRepository;

    @Autowired
    ProductDetailRepository productDetailRepository;

    @Autowired
    UserRepository userRepository;
    @Bean
    public void getDataForDatabase(){
        //add Category;
        Category c1= new Category();
        c1.setName("Đồng Hồ");

        Category c2= new Category();
        c2.setName("Ví Cầm Tay");

        Category c3= new Category();
        c3.setName("Ví Dài");

        Category c4= new Category();
        c4.setName("Balo");

        Category c5= new Category();
        c5.setName("Thắt Lưng");

        Category c6= new Category();
        c6.setName("Giày");

        Category c7= new Category();
        c7.setName("Dép");

        Category c8= new Category();
        c8.setName("Vớ");

        Category c9= new Category();
        c9.setName("Nón");


        categoryRepository.save(c1);
        categoryRepository.save(c2);
        categoryRepository.save(c3);
        categoryRepository.save(c4);
        categoryRepository.save(c5);
        categoryRepository.save(c6);
        categoryRepository.save(c7);
        categoryRepository.save(c8);
        categoryRepository.save(c9);

        //add Product
        Product p1= new Product();
        Product p2= new Product();
        Product p3= new Product();
        Product p4= new Product();
        Product p5= new Product();
        Product p6= new Product();
        Product p7= new Product();
        Product p8= new Product();
        Product p9= new Product();
        Product p10= new Product();
        Product p11= new Product();
        Product p12= new Product();
        Product p13= new Product();
        Product p14= new Product();
        Product p15= new Product();
        Product p16= new Product();
        Product p17= new Product();
        Product p18= new Product();
        Product p19= new Product();
        Product p20= new Product();
        Product p21= new Product();
        Product p22= new Product();
        Product p23= new Product();
        Product p24= new Product();
        Product p25= new Product();
        Product p26= new Product();
        Product p27= new Product();
        Product p28= new Product();
        Product p29= new Product();
        Product p30= new Product();
        Product p31= new Product();
        Product p32= new Product();
        Product p33= new Product();
        Product p34= new Product();
        Product p35= new Product();
        Product p36= new Product();
        Product p37= new Product();
        Product p38= new Product();
        Product p39= new Product();
        Product p40= new Product();
        Product p41= new Product();
        Product p42= new Product();
        Product p43= new Product();
        Product p44= new Product();
        Product p45= new Product();

        p1.setName("Đồng hồ Jacques Lemans");
        p2.setName("Đồng Hồ EPOS SWISS");
        p3.setName("Đồng hồ Diamond D");
        p4.setName("ĐỒNG HỒ PHILIPPE AUGUSTE");
        p5.setName("Đồng hồ Atlantic Swiss");
        p6.setName("VÍ CẦM TAY PIERRE CARDIN");
        p7.setName("VÍ NAM PIERRE CARDIN");
        p8.setName("VÍ DA PIERRE CARDIN");
        p9.setName("VÍ CẦM TAY PIERRE CARDIN");
        p10.setName("VÍ DA PIERRE CARDIN");
        p11.setName("Ví Dài Meron");
        p12.setName("Ví Dài Da Sáp Smool-S");
        p13.setName("Ví Dài Mini - Rainbow");
        p14.setName("Ví Dài LOVE-L");
        p15.setName("SARK - Ví Dài");
        p16.setName("Balo Doanh Nhân");
        p17.setName("Balo Chống Sốc Laptop");
        p18.setName("Balo Du Lịch");
        p19.setName("Balo Du Lịch SimpleCarry");
        p20.setName("BALO DU LỊCH ĐA NĂNG");
        p21.setName("THẮT LƯNG RAF MÀU ĐEN");
        p22.setName("THẮT LƯNG THE ROLL");
        p23.setName("THẮT LƯNG RAF MÀU NÂU");
        p24.setName("THẮT LƯNG DAVID MÀU NÂU");
        p25.setName("THẮT LƯNG STEVEN (ĐEN)");
        p26.setName("GIÀY CONTINENTAL 80");
        p27.setName("GIÀY SUPERSTAR");
        p28.setName("GIÀY SUPERSTAR PRIDE");
        p29.setName("GIÀY STAN SMITH");
        p30.setName("GIÀY STAN SMITH PRIDE");
        p31.setName("Dép Nam Quai Ngang Da Bò");
        p32.setName("Dép Nam Quai Ngang SUPERSTAR");
        p33.setName("Dép Nam Quai Ngang");
        p34.setName("Dép xỏ ngón DUWA");
        p35.setName("Dép Nam Khủng Long");
        p36.setName("Tất Nam Vớ Nam Cổ Dài");
        p37.setName("Tất Nam Vớ Nam Cổ Ngắn");
        p38.setName("Tất Nam Vớ Nam Cổ Dài");
        p39.setName("Tất Nam Cổ Cao Caro");
        p40.setName("Tất Nam 5S Cổ Ngắn");
        p41.setName("Nón bucket");
        p42.setName("Nón tròn FREESIZE");
        p43.setName("Nón bucket");
        p44.setName("MLB -Like Ice");
        p45.setName("Nón Premi3r dadhat");

        p1.setPrice(660);
        p2.setPrice(545);
        p3.setPrice(233);
        p4.setPrice(780);
        p5.setPrice(749);
        p6.setPrice(449);
        p7.setPrice(850);
        p8.setPrice(599);
        p9.setPrice(780);
        p10.setPrice(749);
        p11.setPrice(449);
        p12.setPrice(850);
        p13.setPrice(599);
        p14.setPrice(850);
        p15.setPrice(599);
        p16.setPrice(780);
        p17.setPrice(749);
        p18.setPrice(449);
        p19.setPrice(850);
        p20.setPrice(599);
        p21.setPrice(599);
        p22.setPrice(449);
        p23.setPrice(780);
        p24.setPrice(449);
        p25.setPrice(749);
        p26.setPrice(780);
        p27.setPrice(749);
        p28.setPrice(449);
        p29.setPrice(850);
        p30.setPrice(599);
        p31.setPrice(780);
        p32.setPrice(749);
        p33.setPrice(449);
        p34.setPrice(850);
        p35.setPrice(599);
        p36.setPrice(780);
        p37.setPrice(749);
        p38.setPrice(449);
        p39.setPrice(850);
        p40.setPrice(599);
        p41.setPrice(780);
        p42.setPrice(749);
        p43.setPrice(449);
        p44.setPrice(850);
        p45.setPrice(599);

        p1.setAmount(0);
        p2.setAmount(0);
        p3.setAmount(0);
        p4.setAmount(0);
        p5.setAmount(0);
        p6.setAmount(0);
        p7.setAmount(0);
        p8.setAmount(0);
        p9.setAmount(0);
        p10.setAmount(0);
        p11.setAmount(0);
        p12.setAmount(0);
        p13.setAmount(0);
        p14.setAmount(0);
        p15.setAmount(0);
        p16.setAmount(0);
        p17.setAmount(0);
        p18.setAmount(0);
        p19.setAmount(0);
        p20.setAmount(0);
        p21.setAmount(0);
        p22.setAmount(0);
        p23.setAmount(0);
        p24.setAmount(0);
        p25.setAmount(0);
        p26.setAmount(0);
        p27.setAmount(0);
        p28.setAmount(0);
        p29.setAmount(0);
        p30.setAmount(0);
        p31.setAmount(0);
        p32.setAmount(0);
        p33.setAmount(0);
        p34.setAmount(0);
        p35.setAmount(0);
        p36.setAmount(0);
        p37.setAmount(0);
        p38.setAmount(0);
        p39.setAmount(0);
        p40.setAmount(0);
        p41.setAmount(0);
        p42.setAmount(0);
        p43.setAmount(0);
        p44.setAmount(0);
        p45.setAmount(0);

        p1.setQuantity(20);
        p2.setQuantity(20);
        p3.setQuantity(20);
        p4.setQuantity(20);
        p5.setQuantity(20);
        p6.setQuantity(20);
        p7.setQuantity(20);
        p8.setQuantity(20);
        p9.setQuantity(20);
        p10.setQuantity(20);
        p11.setQuantity(20);
        p12.setQuantity(20);
        p13.setQuantity(20);
        p14.setQuantity(20);
        p15.setQuantity(20);
        p16.setQuantity(20);
        p17.setQuantity(20);
        p18.setQuantity(20);
        p19.setQuantity(20);
        p20.setQuantity(20);
        p21.setQuantity(20);
        p22.setQuantity(20);
        p23.setQuantity(20);
        p24.setQuantity(20);
        p25.setQuantity(20);
        p26.setQuantity(20);
        p27.setQuantity(20);
        p28.setQuantity(20);
        p29.setQuantity(20);
        p30.setQuantity(20);
        p31.setQuantity(20);
        p32.setQuantity(20);
        p33.setQuantity(20);
        p34.setQuantity(20);
        p35.setQuantity(20);
        p36.setQuantity(20);
        p37.setQuantity(20);
        p38.setQuantity(20);
        p39.setQuantity(20);
        p40.setQuantity(20);
        p41.setQuantity(20);
        p42.setQuantity(20);
        p43.setQuantity(20);
        p44.setQuantity(20);
        p45.setQuantity(20);

        p1.setThumbnailPhoto("1_1_1.jpg");
        p2.setThumbnailPhoto("1_2_1.jpg");
        p3.setThumbnailPhoto("1_3_1.jpg");
        p4.setThumbnailPhoto("1_4_1.jpg");
        p5.setThumbnailPhoto("1_5_1.jpg");
        p6.setThumbnailPhoto("2_6_1.jpg");
        p7.setThumbnailPhoto("2_7_1.jpg");
        p8.setThumbnailPhoto("2_8_1.jpg");
        p9.setThumbnailPhoto("2_9_1.jpg");
        p10.setThumbnailPhoto("2_10_1.jpg");
        p11.setThumbnailPhoto("3_11_1.jpg");
        p12.setThumbnailPhoto("3_12_1.jpg");
        p13.setThumbnailPhoto("3_13_1.jpg");
        p14.setThumbnailPhoto("3_14_1.jpg");
        p15.setThumbnailPhoto("3_15_1.jpg");
        p16.setThumbnailPhoto("4_16_1.jpg");
        p17.setThumbnailPhoto("4_17_1.jpg");
        p18.setThumbnailPhoto("4_18_1.jpg");
        p19.setThumbnailPhoto("4_19_1.jpg");
        p20.setThumbnailPhoto("4_20_1.jpg");
        p21.setThumbnailPhoto("5_21_1.jpg");
        p22.setThumbnailPhoto("5_22_1.png");
        p23.setThumbnailPhoto("5_23_1.jpg");
        p24.setThumbnailPhoto("5_24_1.png");
        p25.setThumbnailPhoto("5_25_1.png");
        p26.setThumbnailPhoto("6_26_1.jpg");
        p27.setThumbnailPhoto("6_27_1.jpg");
        p28.setThumbnailPhoto("6_28_1.jpg");
        p29.setThumbnailPhoto("6_29_1.jpg");
        p30.setThumbnailPhoto("6_30_1.jpg");
        p31.setThumbnailPhoto("7_31_1.jpg");
        p32.setThumbnailPhoto("7_32_1.jpg");
        p33.setThumbnailPhoto("7_33_1.jpg");
        p34.setThumbnailPhoto("7_34_1.jpg");
        p35.setThumbnailPhoto("7_35_1.jpg");
        p36.setThumbnailPhoto("8_36_1.jpg");
        p37.setThumbnailPhoto("8_37_1.jpg");
        p38.setThumbnailPhoto("8_38_1.jpg");
        p39.setThumbnailPhoto("8_39_1.jpg");
        p40.setThumbnailPhoto("8_40_1.jpg");
        p41.setThumbnailPhoto("9_41_1.jpg");
        p42.setThumbnailPhoto("9_42_1.jpg");
        p43.setThumbnailPhoto("9_43_1.jpg");
        p44.setThumbnailPhoto("9_44_1.jpg");
        p45.setThumbnailPhoto("9_45_1.jpg");

        p1.setCategory(categoryRepository.getById(1));
        p2.setCategory(categoryRepository.getById(1));
        p3.setCategory(categoryRepository.getById(1));
        p4.setCategory(categoryRepository.getById(1));
        p5.setCategory(categoryRepository.getById(1));
        p6.setCategory(categoryRepository.getById(2));
        p7.setCategory(categoryRepository.getById(2));
        p8.setCategory(categoryRepository.getById(2));
        p9.setCategory(categoryRepository.getById(2));
        p10.setCategory(categoryRepository.getById(2));
        p11.setCategory(categoryRepository.getById(3));
        p12.setCategory(categoryRepository.getById(3));
        p13.setCategory(categoryRepository.getById(3));
        p14.setCategory(categoryRepository.getById(3));
        p15.setCategory(categoryRepository.getById(3));
        p16.setCategory(categoryRepository.getById(4));
        p17.setCategory(categoryRepository.getById(4));
        p18.setCategory(categoryRepository.getById(4));
        p19.setCategory(categoryRepository.getById(4));
        p20.setCategory(categoryRepository.getById(4));
        p21.setCategory(categoryRepository.getById(5));
        p22.setCategory(categoryRepository.getById(5));
        p23.setCategory(categoryRepository.getById(5));
        p24.setCategory(categoryRepository.getById(5));
        p25.setCategory(categoryRepository.getById(5));
        p26.setCategory(categoryRepository.getById(6));
        p27.setCategory(categoryRepository.getById(6));
        p28.setCategory(categoryRepository.getById(6));
        p29.setCategory(categoryRepository.getById(6));
        p30.setCategory(categoryRepository.getById(6));
        p31.setCategory(categoryRepository.getById(7));
        p32.setCategory(categoryRepository.getById(7));
        p33.setCategory(categoryRepository.getById(7));
        p34.setCategory(categoryRepository.getById(7));
        p35.setCategory(categoryRepository.getById(7));
        p36.setCategory(categoryRepository.getById(8));
        p37.setCategory(categoryRepository.getById(8));
        p38.setCategory(categoryRepository.getById(8));
        p39.setCategory(categoryRepository.getById(8));
        p40.setCategory(categoryRepository.getById(8));
        p41.setCategory(categoryRepository.getById(9));
        p42.setCategory(categoryRepository.getById(9));
        p43.setCategory(categoryRepository.getById(9));
        p44.setCategory(categoryRepository.getById(9));
        p45.setCategory(categoryRepository.getById(9));

        productRepository.save(p1);
        productRepository.save(p2);
        productRepository.save(p3);
        productRepository.save(p4);
        productRepository.save(p5);
        productRepository.save(p6);
        productRepository.save(p7);
        productRepository.save(p8);
        productRepository.save(p9);
        productRepository.save(p10);
        productRepository.save(p11);
        productRepository.save(p12);
        productRepository.save(p13);
        productRepository.save(p14);
        productRepository.save(p15);
        productRepository.save(p16);
        productRepository.save(p17);
        productRepository.save(p18);
        productRepository.save(p19);
        productRepository.save(p20);
        productRepository.save(p21);
        productRepository.save(p22);
        productRepository.save(p23);
        productRepository.save(p24);
        productRepository.save(p25);
        productRepository.save(p26);
        productRepository.save(p27);
        productRepository.save(p28);
        productRepository.save(p29);
        productRepository.save(p30);
        productRepository.save(p31);
        productRepository.save(p32);
        productRepository.save(p33);
        productRepository.save(p34);
        productRepository.save(p35);
        productRepository.save(p36);
        productRepository.save(p37);
        productRepository.save(p38);
        productRepository.save(p39);
        productRepository.save(p40);
        productRepository.save(p41);
        productRepository.save(p42);
        productRepository.save(p43);
        productRepository.save(p44);
        productRepository.save(p45);


        //add user
        User u1 = new User();
        User u2 = new User();
        User u3 = new User();
        User u4 = new User();
        User u5 = new User();
        User u6 = new User();
        User u7 = new User();

        u1.setUserName("kietnguyen123");
        u2.setUserName("nghiemnguyen123");
        u3.setUserName("thangpham123");
        u4.setUserName("kiet78911");
        u5.setUserName("kiet789");
        u6.setUserName("admin");
        u7.setUserName("seller");

        u1.setPassWord("key1");
        u2.setPassWord("nghiem123");
        u3.setPassWord("thang123");
        u4.setPassWord("kiet789");
        u5.setPassWord("kiet789");
        u6.setPassWord("admin");
        u7.setPassWord("seller");

        u1.setRole(1);
        u2.setRole(1);
        u3.setRole(1);
        u4.setRole(1);
        u5.setRole(1);
        u6.setRole(3);
        u7.setRole(2);

        userRepository.save(u1);
        userRepository.save(u2);
        userRepository.save(u3);
        userRepository.save(u4);
        userRepository.save(u5);
        userRepository.save(u6);
        userRepository.save(u7);

        //add product image
        ProductImage pi1 = new ProductImage();
        ProductImage pi2 = new ProductImage();
        ProductImage pi3 = new ProductImage();
        ProductImage pi4 = new ProductImage();
        ProductImage pi5 = new ProductImage();
        ProductImage pi6 = new ProductImage();
        ProductImage pi7 = new ProductImage();
        ProductImage pi8 = new ProductImage();
        ProductImage pi9 = new ProductImage();
        ProductImage pi10 = new ProductImage();
        ProductImage pi11 = new ProductImage();
        ProductImage pi12 = new ProductImage();
        ProductImage pi13 = new ProductImage();
        ProductImage pi14 = new ProductImage();
        ProductImage pi15 = new ProductImage();
        ProductImage pi16 = new ProductImage();
        ProductImage pi17 = new ProductImage();
        ProductImage pi18 = new ProductImage();
        ProductImage pi19 = new ProductImage();
        ProductImage pi20 = new ProductImage();
        ProductImage pi21 = new ProductImage();
        ProductImage pi22 = new ProductImage();
        ProductImage pi23 = new ProductImage();
        ProductImage pi24 = new ProductImage();
        ProductImage pi25 = new ProductImage();
        ProductImage pi26 = new ProductImage();
        ProductImage pi27 = new ProductImage();
        ProductImage pi28 = new ProductImage();
        ProductImage pi29 = new ProductImage();
        ProductImage pi30 = new ProductImage();
        ProductImage pi31 = new ProductImage();
        ProductImage pi32 = new ProductImage();
        ProductImage pi33 = new ProductImage();
        ProductImage pi34 = new ProductImage();
        ProductImage pi35 = new ProductImage();
        ProductImage pi36 = new ProductImage();
        ProductImage pi37 = new ProductImage();
        ProductImage pi38 = new ProductImage();
        ProductImage pi39 = new ProductImage();
        ProductImage pi40 = new ProductImage();
        ProductImage pi41 = new ProductImage();
        ProductImage pi42 = new ProductImage();
        ProductImage pi43 = new ProductImage();
        ProductImage pi44 = new ProductImage();
        ProductImage pi45 = new ProductImage();
        ProductImage pi46 = new ProductImage();
        ProductImage pi47 = new ProductImage();
        ProductImage pi48 = new ProductImage();
        ProductImage pi49 = new ProductImage();
        ProductImage pi50 = new ProductImage();
        ProductImage pi51 = new ProductImage();
        ProductImage pi52 = new ProductImage();
        ProductImage pi53 = new ProductImage();
        ProductImage pi54 = new ProductImage();
        ProductImage pi55 = new ProductImage();
        ProductImage pi56 = new ProductImage();
        ProductImage pi57 = new ProductImage();
        ProductImage pi58 = new ProductImage();
        ProductImage pi59 = new ProductImage();
        ProductImage pi60 = new ProductImage();
        ProductImage pi61 = new ProductImage();
        ProductImage pi62 = new ProductImage();
        ProductImage pi63 = new ProductImage();
        ProductImage pi64 = new ProductImage();
        ProductImage pi65 = new ProductImage();
        ProductImage pi66 = new ProductImage();
        ProductImage pi67 = new ProductImage();
        ProductImage pi68 = new ProductImage();
        ProductImage pi69 = new ProductImage();
        ProductImage pi70 = new ProductImage();
        ProductImage pi71 = new ProductImage();
        ProductImage pi72 = new ProductImage();
        ProductImage pi73 = new ProductImage();
        ProductImage pi74 = new ProductImage();
        ProductImage pi75 = new ProductImage();
        ProductImage pi76 = new ProductImage();
        ProductImage pi77 = new ProductImage();
        ProductImage pi78 = new ProductImage();
        ProductImage pi79 = new ProductImage();
        ProductImage pi80 = new ProductImage();
        ProductImage pi81 = new ProductImage();
        ProductImage pi82 = new ProductImage();
        ProductImage pi83 = new ProductImage();
        ProductImage pi84 = new ProductImage();
        ProductImage pi85 = new ProductImage();
        ProductImage pi86 = new ProductImage();
        ProductImage pi87 = new ProductImage();
        ProductImage pi88 = new ProductImage();
        ProductImage pi89 = new ProductImage();
        ProductImage pi90 = new ProductImage();
        ProductImage pi91 = new ProductImage();
        ProductImage pi92 = new ProductImage();
        ProductImage pi93 = new ProductImage();
        ProductImage pi94 = new ProductImage();
        ProductImage pi95 = new ProductImage();
        ProductImage pi96 = new ProductImage();
        ProductImage pi97 = new ProductImage();
        ProductImage pi98 = new ProductImage();
        ProductImage pi99 = new ProductImage();
        ProductImage pi100 = new ProductImage();
        ProductImage pi101 = new ProductImage();
        ProductImage pi102 = new ProductImage();
        ProductImage pi103 = new ProductImage();
        ProductImage pi104 = new ProductImage();
        ProductImage pi105 = new ProductImage();
        ProductImage pi106 = new ProductImage();
        ProductImage pi107 = new ProductImage();
        ProductImage pi108 = new ProductImage();
        ProductImage pi109 = new ProductImage();
        ProductImage pi110 = new ProductImage();
        ProductImage pi111 = new ProductImage();
        ProductImage pi112 = new ProductImage();
        ProductImage pi113 = new ProductImage();
        ProductImage pi114 = new ProductImage();
        ProductImage pi115 = new ProductImage();
        ProductImage pi116 = new ProductImage();
        ProductImage pi117 = new ProductImage();
        ProductImage pi118 = new ProductImage();
        ProductImage pi119 = new ProductImage();
        ProductImage pi120 = new ProductImage();
        ProductImage pi121 = new ProductImage();
        ProductImage pi122 = new ProductImage();
        ProductImage pi123 = new ProductImage();
        ProductImage pi124 = new ProductImage();
        ProductImage pi125 = new ProductImage();
        ProductImage pi126 = new ProductImage();
        ProductImage pi127 = new ProductImage();
        ProductImage pi128 = new ProductImage();
        ProductImage pi129 = new ProductImage();
        ProductImage pi130 = new ProductImage();
        ProductImage pi131 = new ProductImage();
        ProductImage pi132 = new ProductImage();
        ProductImage pi133 = new ProductImage();
        ProductImage pi134 = new ProductImage();
        ProductImage pi135 = new ProductImage();
        ProductImage pi136 = new ProductImage();
        ProductImage pi137 = new ProductImage();
        ProductImage pi138 = new ProductImage();
        ProductImage pi139 = new ProductImage();
        ProductImage pi140 = new ProductImage();
        ProductImage pi141 = new ProductImage();
        ProductImage pi142 = new ProductImage();
        ProductImage pi143 = new ProductImage();
        ProductImage pi144 = new ProductImage();
        ProductImage pi145 = new ProductImage();
        ProductImage pi146 = new ProductImage();
        ProductImage pi147 = new ProductImage();
        ProductImage pi148 = new ProductImage();
        ProductImage pi149 = new ProductImage();
        ProductImage pi150 = new ProductImage();
        ProductImage pi151 = new ProductImage();
        ProductImage pi152 = new ProductImage();
        ProductImage pi153 = new ProductImage();
        ProductImage pi154 = new ProductImage();
        ProductImage pi155 = new ProductImage();
        ProductImage pi156 = new ProductImage();
        ProductImage pi157 = new ProductImage();
        ProductImage pi158 = new ProductImage();
        ProductImage pi159 = new ProductImage();
        ProductImage pi160 = new ProductImage();
        ProductImage pi161 = new ProductImage();
        ProductImage pi162 = new ProductImage();
        ProductImage pi163 = new ProductImage();
        ProductImage pi164 = new ProductImage();
        ProductImage pi165 = new ProductImage();
        ProductImage pi166 = new ProductImage();
        ProductImage pi167 = new ProductImage();
        ProductImage pi168 = new ProductImage();
        ProductImage pi169 = new ProductImage();
        ProductImage pi170 = new ProductImage();
        ProductImage pi171 = new ProductImage();
        ProductImage pi172 = new ProductImage();
        ProductImage pi173 = new ProductImage();
        ProductImage pi174 = new ProductImage();
        ProductImage pi175 = new ProductImage();
        ProductImage pi176 = new ProductImage();
        ProductImage pi177 = new ProductImage();
        ProductImage pi178 = new ProductImage();
        ProductImage pi179 = new ProductImage();
        ProductImage pi180 = new ProductImage();

        pi1.setLink("1_1_1.jpg");
        pi2.setLink("1_1_2.jpg");
        pi3.setLink("1_1_3.jpg");
        pi4.setLink("1_1_4.jpg");
        pi5.setLink("1_2_1.jpg");
        pi6.setLink("1_2_2.jpg");
        pi7.setLink("1_2_3.jpg");
        pi8.setLink("1_2_4.jpg");
        pi9.setLink("1_3_1.jpg");
        pi10.setLink("1_3_2.jpg");
        pi11.setLink("1_3_3.jpg");
        pi12.setLink("1_3_4.jpg");
        pi13.setLink("1_4_1.jpg");
        pi14.setLink("1_4_2.jpg");
        pi15.setLink("1_4_3.jpg");
        pi16.setLink("1_4_4.jpg");
        pi17.setLink("1_5_1.jpg");
        pi18.setLink("1_5_2.jpg");
        pi19.setLink("1_5_3.jpg");
        pi20.setLink("1_5_4.jpg");
        pi21.setLink("2_6_1.jpg");
        pi22.setLink("2_6_2.jpg");
        pi23.setLink("2_6_3.jpg");
        pi24.setLink("2_6_4.jpg");
        pi25.setLink("2_7_1.jpg");
        pi26.setLink("2_7_2.jpg");
        pi27.setLink("2_7_3.jpg");
        pi28.setLink("2_7_4.jpg");
        pi29.setLink("2_8_1.jpg");
        pi30.setLink("2_8_2.jpg");
        pi31.setLink("2_8_3.jpg");
        pi32.setLink("2_8_4.jpg");
        pi33.setLink("2_9_1.jpg");
        pi34.setLink("2_9_2.jpg");
        pi35.setLink("2_9_3.jpg");
        pi36.setLink("2_9_4.jpg");
        pi37.setLink("2_10_1.jpg");
        pi38.setLink("2_10_2.jpg");
        pi39.setLink("2_10_3.jpg");
        pi40.setLink("2_10_4.jpg");
        pi41.setLink("3_11_1.jpg");
        pi42.setLink("3_11_2.jpg");
        pi43.setLink("3_11_3.jpg");
        pi44.setLink("3_11_4.jpg");
        pi45.setLink("3_12_1.jpg");
        pi46.setLink("3_12_2.jpg");
        pi47.setLink("3_12_3.jpg");
        pi48.setLink("3_12_4.jpg");
        pi49.setLink("3_13_1.jpg");
        pi50.setLink("3_13_2.jpg");
        pi51.setLink("3_13_3.jpg");
        pi52.setLink("3_13_4.jpg");
        pi53.setLink("3_14_1.jpg");
        pi54.setLink("3_14_2.jpg");
        pi55.setLink("3_14_3.jpg");
        pi56.setLink("3_14_4.jpg");
        pi57.setLink("3_15_1.jpg");
        pi58.setLink("3_15_2.jpg");
        pi59.setLink("3_15_3.jpg");
        pi60.setLink("3_15_4.jpg");
        pi61.setLink("4_16_1.jpg");
        pi62.setLink("4_16_2.jpg");
        pi63.setLink("4_16_3.jpg");
        pi64.setLink("4_16_4.jpg");
        pi65.setLink("4_17_1.jpg");
        pi66.setLink("4_17_2.jpg");
        pi67.setLink("4_17_3.jpg");
        pi68.setLink("4_17_4.jpg");
        pi69.setLink("4_18_1.jpg");
        pi70.setLink("4_18_2.jpg");
        pi71.setLink("4_18_3.jpg");
        pi72.setLink("4_18_4.jpg");
        pi73.setLink("4_19_1.jpg");
        pi74.setLink("4_19_2.jpg");
        pi75.setLink("4_19_3.jpg");
        pi76.setLink("4_19_4.jpg");
        pi77.setLink("4_20_1.jpg");
        pi78.setLink("4_20_2.jpg");
        pi79.setLink("4_20_3.jpg");
        pi80.setLink("4_20_4.jpg");
        pi81.setLink("5_21_1.jpg");
        pi82.setLink("5_21_2.jpg");
        pi83.setLink("5_21_3.jpg");
        pi84.setLink("5_21_4.jpg");
        pi85.setLink("5_22_1.png");
        pi86.setLink("5_22_2.png");
        pi87.setLink("5_22_3.png");
        pi88.setLink("5_22_4.png");
        pi89.setLink("5_23_1.jpg");
        pi90.setLink("5_23_2.jpg");
        pi91.setLink("5_23_3.jpg");
        pi92.setLink("5_23_4.jpg");
        pi93.setLink("5_24_1.png");
        pi94.setLink("5_24_2.png");
        pi95.setLink("5_24_3.png");
        pi96.setLink("5_24_4.png");
        pi97.setLink("5_25_1.png");
        pi98.setLink("5_25_2.png");
        pi99.setLink("5_25_3.png");
        pi100.setLink("5_25_4.png");
        pi101.setLink("6_26_1.jpg");
        pi102.setLink("6_26_2.jpg");
        pi103.setLink("6_26_3.jpg");
        pi104.setLink("6_26_4.jpg");
        pi105.setLink("6_27_1.jpg");
        pi106.setLink("6_27_2.jpg");
        pi107.setLink("6_27_3.jpg");
        pi108.setLink("6_27_4.jpg");
        pi109.setLink("6_28_1.jpg");
        pi110.setLink("6_28_2.jpg");
        pi111.setLink("6_28_3.jpg");
        pi112.setLink("6_28_4.jpg");
        pi113.setLink("6_29_1.jpg");
        pi114.setLink("6_29_2.jpg");
        pi115.setLink("6_29_3.jpg");
        pi116.setLink("6_29_4.jpg");
        pi117.setLink("6_30_1.jpg");
        pi118.setLink("6_30_2.jpg");
        pi119.setLink("6_30_3.jpg");
        pi120.setLink("6_30_4.jpg");
        pi121.setLink("7_31_1.jpg");
        pi122.setLink("7_31_2.jpg");
        pi123.setLink("7_31_3.jpg");
        pi124.setLink("7_31_4.jpg");
        pi125.setLink("7_32_1.jpg");
        pi126.setLink("7_32_2.jpg");
        pi127.setLink("7_32_3.jpg");
        pi128.setLink("7_32_4.jpg");
        pi129.setLink("7_33_1.jpg");
        pi130.setLink("7_33_2.jpg");
        pi131.setLink("7_33_3.jpg");
        pi132.setLink("7_33_4.jpg");
        pi133.setLink("7_34_1.jpg");
        pi134.setLink("7_34_2.jpg");
        pi135.setLink("7_34_3.jpg");
        pi136.setLink("7_34_4.jpg");
        pi137.setLink("7_35_1.jpg");
        pi138.setLink("7_35_2.jpg");
        pi139.setLink("7_35_3.jpg");
        pi140.setLink("7_35_4.jpg");
        pi141.setLink("8_36_1.jpg");
        pi142.setLink("8_36_2.jpg");
        pi143.setLink("8_36_3.jpg");
        pi144.setLink("8_36_4.jpg");
        pi145.setLink("8_37_1.jpg");
        pi146.setLink("8_37_2.jpg");
        pi147.setLink("8_37_3.jpg");
        pi148.setLink("8_37_4.jpg");
        pi149.setLink("8_38_1.jpg");
        pi150.setLink("8_38_2.jpg");
        pi151.setLink("8_38_3.jpg");
        pi152.setLink("8_38_4.jpg");
        pi153.setLink("8_39_1.jpg");
        pi154.setLink("8_39_2.jpg");
        pi155.setLink("8_39_3.jpg");
        pi156.setLink("8_39_4.jpg");
        pi157.setLink("8_40_1.jpg");
        pi158.setLink("8_40_2.jpg");
        pi159.setLink("8_40_3.jpg");
        pi160.setLink("8_40_4.jpg");
        pi161.setLink("9_41_1.jpg");
        pi162.setLink("9_41_2.jpg");
        pi163.setLink("9_41_3.jpg");
        pi164.setLink("9_41_4.jpg");
        pi165.setLink("9_42_1.jpg");
        pi166.setLink("9_42_2.jpg");
        pi167.setLink("9_42_3.jpg");
        pi168.setLink("9_42_4.jpg");
        pi169.setLink("9_43_1.jpg");
        pi170.setLink("9_43_2.jpg");
        pi171.setLink("9_43_3.jpg");
        pi172.setLink("9_43_4.jpg");
        pi173.setLink("9_44_1.jpg");
        pi174.setLink("9_44_2.jpg");
        pi175.setLink("9_44_3.jpg");
        pi176.setLink("9_44_4.jpg");
        pi177.setLink("9_45_1.jpg");
        pi178.setLink("9_45_2.jpg");
        pi179.setLink("9_45_3.jpg");
        pi180.setLink("9_45_4.jpg");

        pi1.setProduct(productRepository.getById(1));
        pi2.setProduct(productRepository.getById(1));
        pi3.setProduct(productRepository.getById(1));
        pi4.setProduct(productRepository.getById(1));
        pi5.setProduct(productRepository.getById(2));
        pi6.setProduct(productRepository.getById(2));
        pi7.setProduct(productRepository.getById(2));
        pi8.setProduct(productRepository.getById(2));
        pi9.setProduct(productRepository.getById(3));
        pi10.setProduct(productRepository.getById(3));
        pi11.setProduct(productRepository.getById(3));
        pi12.setProduct(productRepository.getById(3));
        pi13.setProduct(productRepository.getById(4));
        pi14.setProduct(productRepository.getById(4));
        pi15.setProduct(productRepository.getById(4));
        pi16.setProduct(productRepository.getById(4));
        pi17.setProduct(productRepository.getById(5));
        pi18.setProduct(productRepository.getById(5));
        pi19.setProduct(productRepository.getById(5));
        pi20.setProduct(productRepository.getById(5));
        pi21.setProduct(productRepository.getById(6));
        pi22.setProduct(productRepository.getById(6));
        pi23.setProduct(productRepository.getById(6));
        pi24.setProduct(productRepository.getById(6));
        pi25.setProduct(productRepository.getById(7));
        pi26.setProduct(productRepository.getById(7));
        pi27.setProduct(productRepository.getById(7));
        pi28.setProduct(productRepository.getById(7));
        pi29.setProduct(productRepository.getById(8));
        pi30.setProduct(productRepository.getById(8));
        pi31.setProduct(productRepository.getById(8));
        pi32.setProduct(productRepository.getById(8));
        pi33.setProduct(productRepository.getById(9));
        pi34.setProduct(productRepository.getById(9));
        pi35.setProduct(productRepository.getById(9));
        pi36.setProduct(productRepository.getById(9));
        pi37.setProduct(productRepository.getById(10));
        pi38.setProduct(productRepository.getById(10));
        pi39.setProduct(productRepository.getById(10));
        pi40.setProduct(productRepository.getById(10));
        pi41.setProduct(productRepository.getById(11));
        pi42.setProduct(productRepository.getById(11));
        pi43.setProduct(productRepository.getById(11));
        pi44.setProduct(productRepository.getById(11));
        pi45.setProduct(productRepository.getById(12));
        pi46.setProduct(productRepository.getById(12));
        pi47.setProduct(productRepository.getById(12));
        pi48.setProduct(productRepository.getById(12));
        pi49.setProduct(productRepository.getById(13));
        pi50.setProduct(productRepository.getById(13));
        pi51.setProduct(productRepository.getById(13));
        pi52.setProduct(productRepository.getById(13));
        pi53.setProduct(productRepository.getById(14));
        pi54.setProduct(productRepository.getById(14));
        pi55.setProduct(productRepository.getById(14));
        pi56.setProduct(productRepository.getById(14));
        pi57.setProduct(productRepository.getById(15));
        pi58.setProduct(productRepository.getById(15));
        pi59.setProduct(productRepository.getById(15));
        pi60.setProduct(productRepository.getById(15));
        pi61.setProduct(productRepository.getById(16));
        pi62.setProduct(productRepository.getById(16));
        pi63.setProduct(productRepository.getById(16));
        pi64.setProduct(productRepository.getById(16));
        pi65.setProduct(productRepository.getById(17));
        pi66.setProduct(productRepository.getById(17));
        pi67.setProduct(productRepository.getById(17));
        pi68.setProduct(productRepository.getById(17));
        pi69.setProduct(productRepository.getById(18));
        pi70.setProduct(productRepository.getById(18));
        pi71.setProduct(productRepository.getById(18));
        pi72.setProduct(productRepository.getById(18));
        pi73.setProduct(productRepository.getById(19));
        pi74.setProduct(productRepository.getById(19));
        pi75.setProduct(productRepository.getById(19));
        pi76.setProduct(productRepository.getById(19));
        pi77.setProduct(productRepository.getById(20));
        pi78.setProduct(productRepository.getById(20));
        pi79.setProduct(productRepository.getById(20));
        pi80.setProduct(productRepository.getById(20));
        pi81.setProduct(productRepository.getById(21));
        pi82.setProduct(productRepository.getById(21));
        pi83.setProduct(productRepository.getById(21));
        pi84.setProduct(productRepository.getById(21));
        pi85.setProduct(productRepository.getById(22));
        pi86.setProduct(productRepository.getById(22));
        pi87.setProduct(productRepository.getById(22));
        pi88.setProduct(productRepository.getById(22));
        pi89.setProduct(productRepository.getById(23));
        pi90.setProduct(productRepository.getById(23));
        pi91.setProduct(productRepository.getById(23));
        pi92.setProduct(productRepository.getById(23));
        pi93.setProduct(productRepository.getById(24));
        pi94.setProduct(productRepository.getById(24));
        pi95.setProduct(productRepository.getById(24));
        pi96.setProduct(productRepository.getById(24));
        pi97.setProduct(productRepository.getById(25));
        pi98.setProduct(productRepository.getById(25));
        pi99.setProduct(productRepository.getById(25));
        pi100.setProduct(productRepository.getById(25));
        pi101.setProduct(productRepository.getById(26));
        pi102.setProduct(productRepository.getById(26));
        pi103.setProduct(productRepository.getById(26));
        pi104.setProduct(productRepository.getById(26));
        pi105.setProduct(productRepository.getById(27));
        pi106.setProduct(productRepository.getById(27));
        pi107.setProduct(productRepository.getById(27));
        pi108.setProduct(productRepository.getById(27));
        pi109.setProduct(productRepository.getById(28));
        pi110.setProduct(productRepository.getById(28));
        pi111.setProduct(productRepository.getById(28));
        pi112.setProduct(productRepository.getById(28));
        pi113.setProduct(productRepository.getById(29));
        pi114.setProduct(productRepository.getById(29));
        pi115.setProduct(productRepository.getById(29));
        pi116.setProduct(productRepository.getById(29));
        pi117.setProduct(productRepository.getById(30));
        pi118.setProduct(productRepository.getById(30));
        pi119.setProduct(productRepository.getById(30));
        pi120.setProduct(productRepository.getById(30));
        pi121.setProduct(productRepository.getById(31));
        pi122.setProduct(productRepository.getById(31));
        pi123.setProduct(productRepository.getById(31));
        pi124.setProduct(productRepository.getById(31));
        pi125.setProduct(productRepository.getById(32));
        pi126.setProduct(productRepository.getById(32));
        pi127.setProduct(productRepository.getById(32));
        pi128.setProduct(productRepository.getById(32));
        pi129.setProduct(productRepository.getById(33));
        pi130.setProduct(productRepository.getById(33));
        pi131.setProduct(productRepository.getById(33));
        pi132.setProduct(productRepository.getById(33));
        pi133.setProduct(productRepository.getById(34));
        pi134.setProduct(productRepository.getById(34));
        pi135.setProduct(productRepository.getById(34));
        pi136.setProduct(productRepository.getById(34));
        pi137.setProduct(productRepository.getById(35));
        pi138.setProduct(productRepository.getById(35));
        pi139.setProduct(productRepository.getById(35));
        pi140.setProduct(productRepository.getById(35));
        pi141.setProduct(productRepository.getById(36));
        pi142.setProduct(productRepository.getById(36));
        pi143.setProduct(productRepository.getById(36));
        pi144.setProduct(productRepository.getById(36));
        pi145.setProduct(productRepository.getById(37));
        pi146.setProduct(productRepository.getById(37));
        pi147.setProduct(productRepository.getById(37));
        pi148.setProduct(productRepository.getById(37));
        pi149.setProduct(productRepository.getById(38));
        pi150.setProduct(productRepository.getById(38));
        pi151.setProduct(productRepository.getById(38));
        pi152.setProduct(productRepository.getById(38));
        pi153.setProduct(productRepository.getById(39));
        pi154.setProduct(productRepository.getById(39));
        pi155.setProduct(productRepository.getById(39));
        pi156.setProduct(productRepository.getById(39));
        pi157.setProduct(productRepository.getById(40));
        pi158.setProduct(productRepository.getById(40));
        pi159.setProduct(productRepository.getById(40));
        pi160.setProduct(productRepository.getById(40));
        pi161.setProduct(productRepository.getById(41));
        pi162.setProduct(productRepository.getById(41));
        pi163.setProduct(productRepository.getById(41));
        pi164.setProduct(productRepository.getById(41));
        pi165.setProduct(productRepository.getById(42));
        pi166.setProduct(productRepository.getById(42));
        pi167.setProduct(productRepository.getById(42));
        pi168.setProduct(productRepository.getById(42));
        pi169.setProduct(productRepository.getById(43));
        pi170.setProduct(productRepository.getById(43));
        pi171.setProduct(productRepository.getById(43));
        pi172.setProduct(productRepository.getById(43));
        pi173.setProduct(productRepository.getById(44));
        pi174.setProduct(productRepository.getById(44));
        pi175.setProduct(productRepository.getById(44));
        pi176.setProduct(productRepository.getById(44));
        pi177.setProduct(productRepository.getById(45));
        pi178.setProduct(productRepository.getById(45));
        pi179.setProduct(productRepository.getById(45));
        pi180.setProduct(productRepository.getById(45));

        productImageRepository.save(pi1);
        productImageRepository.save(pi2);
        productImageRepository.save(pi3);
        productImageRepository.save(pi4);
        productImageRepository.save(pi5);
        productImageRepository.save(pi6);
        productImageRepository.save(pi7);
        productImageRepository.save(pi8);
        productImageRepository.save(pi9);
        productImageRepository.save(pi10);
        productImageRepository.save(pi11);
        productImageRepository.save(pi12);
        productImageRepository.save(pi13);
        productImageRepository.save(pi14);
        productImageRepository.save(pi15);
        productImageRepository.save(pi16);
        productImageRepository.save(pi17);
        productImageRepository.save(pi18);
        productImageRepository.save(pi19);
        productImageRepository.save(pi20);
        productImageRepository.save(pi21);
        productImageRepository.save(pi22);
        productImageRepository.save(pi23);
        productImageRepository.save(pi24);
        productImageRepository.save(pi25);
        productImageRepository.save(pi26);
        productImageRepository.save(pi27);
        productImageRepository.save(pi28);
        productImageRepository.save(pi29);
        productImageRepository.save(pi30);
        productImageRepository.save(pi31);
        productImageRepository.save(pi32);
        productImageRepository.save(pi33);
        productImageRepository.save(pi34);
        productImageRepository.save(pi35);
        productImageRepository.save(pi36);
        productImageRepository.save(pi37);
        productImageRepository.save(pi38);
        productImageRepository.save(pi39);
        productImageRepository.save(pi40);
        productImageRepository.save(pi41);
        productImageRepository.save(pi42);
        productImageRepository.save(pi43);
        productImageRepository.save(pi44);
        productImageRepository.save(pi45);
        productImageRepository.save(pi46);
        productImageRepository.save(pi47);
        productImageRepository.save(pi48);
        productImageRepository.save(pi49);
        productImageRepository.save(pi50);
        productImageRepository.save(pi51);
        productImageRepository.save(pi52);
        productImageRepository.save(pi53);
        productImageRepository.save(pi54);
        productImageRepository.save(pi55);
        productImageRepository.save(pi56);
        productImageRepository.save(pi57);
        productImageRepository.save(pi58);
        productImageRepository.save(pi59);
        productImageRepository.save(pi60);
        productImageRepository.save(pi61);
        productImageRepository.save(pi62);
        productImageRepository.save(pi63);
        productImageRepository.save(pi64);
        productImageRepository.save(pi65);
        productImageRepository.save(pi66);
        productImageRepository.save(pi67);
        productImageRepository.save(pi68);
        productImageRepository.save(pi69);
        productImageRepository.save(pi70);
        productImageRepository.save(pi71);
        productImageRepository.save(pi72);
        productImageRepository.save(pi73);
        productImageRepository.save(pi74);
        productImageRepository.save(pi75);
        productImageRepository.save(pi76);
        productImageRepository.save(pi77);
        productImageRepository.save(pi78);
        productImageRepository.save(pi79);
        productImageRepository.save(pi80);
        productImageRepository.save(pi81);
        productImageRepository.save(pi82);
        productImageRepository.save(pi83);
        productImageRepository.save(pi84);
        productImageRepository.save(pi85);
        productImageRepository.save(pi86);
        productImageRepository.save(pi87);
        productImageRepository.save(pi88);
        productImageRepository.save(pi89);
        productImageRepository.save(pi90);
        productImageRepository.save(pi91);
        productImageRepository.save(pi92);
        productImageRepository.save(pi93);
        productImageRepository.save(pi94);
        productImageRepository.save(pi95);
        productImageRepository.save(pi96);
        productImageRepository.save(pi97);
        productImageRepository.save(pi98);
        productImageRepository.save(pi99);
        productImageRepository.save(pi100);
        productImageRepository.save(pi101);
        productImageRepository.save(pi102);
        productImageRepository.save(pi103);
        productImageRepository.save(pi104);
        productImageRepository.save(pi105);
        productImageRepository.save(pi106);
        productImageRepository.save(pi107);
        productImageRepository.save(pi108);
        productImageRepository.save(pi109);
        productImageRepository.save(pi110);
        productImageRepository.save(pi111);
        productImageRepository.save(pi112);
        productImageRepository.save(pi113);
        productImageRepository.save(pi114);
        productImageRepository.save(pi115);
        productImageRepository.save(pi116);
        productImageRepository.save(pi117);
        productImageRepository.save(pi118);
        productImageRepository.save(pi119);
        productImageRepository.save(pi120);
        productImageRepository.save(pi121);
        productImageRepository.save(pi122);
        productImageRepository.save(pi123);
        productImageRepository.save(pi124);
        productImageRepository.save(pi125);
        productImageRepository.save(pi126);
        productImageRepository.save(pi127);
        productImageRepository.save(pi128);
        productImageRepository.save(pi129);
        productImageRepository.save(pi130);
        productImageRepository.save(pi131);
        productImageRepository.save(pi132);
        productImageRepository.save(pi133);
        productImageRepository.save(pi134);
        productImageRepository.save(pi135);
        productImageRepository.save(pi136);
        productImageRepository.save(pi137);
        productImageRepository.save(pi138);
        productImageRepository.save(pi139);
        productImageRepository.save(pi140);
        productImageRepository.save(pi141);
        productImageRepository.save(pi142);
        productImageRepository.save(pi143);
        productImageRepository.save(pi144);
        productImageRepository.save(pi145);
        productImageRepository.save(pi146);
        productImageRepository.save(pi147);
        productImageRepository.save(pi148);
        productImageRepository.save(pi149);
        productImageRepository.save(pi150);
        productImageRepository.save(pi151);
        productImageRepository.save(pi152);
        productImageRepository.save(pi153);
        productImageRepository.save(pi154);
        productImageRepository.save(pi155);
        productImageRepository.save(pi156);
        productImageRepository.save(pi157);
        productImageRepository.save(pi158);
        productImageRepository.save(pi159);
        productImageRepository.save(pi160);
        productImageRepository.save(pi161);
        productImageRepository.save(pi162);
        productImageRepository.save(pi163);
        productImageRepository.save(pi164);
        productImageRepository.save(pi165);
        productImageRepository.save(pi166);
        productImageRepository.save(pi167);
        productImageRepository.save(pi168);
        productImageRepository.save(pi169);
        productImageRepository.save(pi170);
        productImageRepository.save(pi171);
        productImageRepository.save(pi172);
        productImageRepository.save(pi173);
        productImageRepository.save(pi174);
        productImageRepository.save(pi175);
        productImageRepository.save(pi176);
        productImageRepository.save(pi177);
        productImageRepository.save(pi178);
        productImageRepository.save(pi179);
        productImageRepository.save(pi180);

        //add product detail
        ProductDetail pd1 = new ProductDetail();
        ProductDetail pd2 = new ProductDetail();
        ProductDetail pd3 = new ProductDetail();
        ProductDetail pd4 = new ProductDetail();
        ProductDetail pd5 = new ProductDetail();
        ProductDetail pd6 = new ProductDetail();

        pd1.setBrand("Hublob");
        pd2.setBrand("Rolex");
        pd3.setBrand("Rolex");
        pd4.setBrand("Hublob");
        pd5.setBrand("Nike");
        pd6.setBrand("Nike");

        pd1.setColor("Đen Xanh");
        pd2.setColor("Trắng");
        pd3.setColor("Đen Xanh");
        pd4.setColor("Đen Xanh");
        pd5.setColor("Trắng");
        pd6.setColor("Trắng");

        pd1.setMaterial("Vàng");
        pd2.setMaterial("Vàng");
        pd3.setMaterial("Vàng");
        pd4.setMaterial("Vàng");
        pd5.setMaterial("Vải");
        pd6.setMaterial("Vải");

        pd1.setDescription("Mang lại vẻ sành điệu, lịch lãm và đầy nam tính cho người đàn ông hiện đại.");
        pd2.setDescription("Mang lại vẻ sành điệu, lịch lãm và đầy nam tính cho người đàn ông hiện đại.");
        pd3.setDescription("Mang lại vẻ sành điệu, lịch lãm và đầy nam tính cho người đàn ông hiện đại.");
        pd4.setDescription("Mang lại vẻ sành điệu, lịch lãm và đầy nam tính cho người đàn ông hiện đại.");
        pd5.setDescription("Mang lại vẻ sành điệu, lịch lãm và đầy nam tính cho người đàn ông hiện đại.");
        pd6.setDescription("Mang lại vẻ sành điệu, lịch lãm và đầy nam tính cho người đàn ông hiện đại.");

        productDetailRepository.save(pd1);
        productDetailRepository.save(pd2);
        productDetailRepository.save(pd3);
        productDetailRepository.save(pd4);
        productDetailRepository.save(pd5);
        productDetailRepository.save(pd6);
    }
}
